Repository DDD-4/4servings-android, pull requests merged in 2020-09, with the labels that each got.

#18 Fix issue bug
  presentation/src/main/java/com/ddd4/dropit/presentation/ui/category/CategoryActivity.kt
  presentation/src/main/java/com/ddd4/dropit/presentation/ui/category/CategoryViewModel.kt
  presentation/src/main/java/com/ddd4/dropit/presentation/ui/detailFolder/FolderItemDetailActivity.kt
  presentation/src/main/java/com/ddd4/dropit/presentation/ui/folder/FolderActivity.kt
  presentation/src/main/java/com/ddd4/dropit/presentation/ui/folder/FolderBinding.kt
  presentation/src/main/java/com/ddd4/dropit/presentation/util/DateExt.kt
  presentation/src/main/java/com/ddd4/dropit/presentation/util/GlideImageExt.kt
  presentation/src/main/res/drawable/bg_white_border.xml
  presentation/src/main/res/layout/activity_category.xml
  presentation/src/main/res/layout/activity_folder_item_detail.xml
Labels: bug

#20 fix. folder item unselect
  presentation/src/main/java/com/ddd4/dropit/presentation/ui/folder/FolderActivity.kt
  presentation/src/main/java/com/ddd4/dropit/presentation/ui/folder/FolderAdapter.kt
  presentation/src/main/java/com/ddd4/dropit/presentation/ui/folder/FolderViewModel.kt
Labels: bug

#37 feat: Create Action Release file(.yml) & Update Version
  .github/workflows/release_bundle.yml
  common-android.gradle
  dependencies.gradle
Labels: feature

#38 Feature/firebases analytics crashlytics
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  build.gradle
  common-android.gradle
  dependencies.gradle
  presentation/build.gradle
Labels: feature

#40 Modify/34/add section selection
  presentation/src/main/res/drawable/bg_category_activate.xml
  presentation/src/main/res/drawable/bg_subcategory_activate.xml
  presentation/src/main/res/layout/fragment_add_section.xml
  presentation/src/main/res/layout/row_add_category.xml
  presentation/src/main/res/layout/row_add_subcategory.xml
Labels: modify

#43 fix. 카테고리 아이템 목록 겹침 현상 수정, 코드 수정
  presentation/src/main/java/com/ddd4/dropit/presentation/ui/add/adapter/AddCategoryAdapter.kt
Labels: bug
